[user]
name = "NTBBloodbath"
email = "bloodbathalchemist@protonmail.com"

[signing]
behavior = "own"
backend = "gpg"
key = "18D6730BC846AAC5"

[ui]
editor = "nvim"
log-word-wrap = true
default-command = "log"

[aliases]
sync-master = ["util", "exec", "--", "bash", "-c", """
#!/usr/bin/env bash
set -euo pipefail
jj git fetch && jj new master
""", ""]
sync-main = ["util", "exec", "--", "bash", "-c", """
#!/usr/bin/env bash
set -euo pipefail
jj git fetch && jj new main
""", ""]

# [experimental-advance-branches]
# enabled-branches = ["glob:*"]
# enabled-branches = ["main", "master"]

tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]
[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'
